rem Ce fichier vas permettre de supprimer les differentes tables crée dans notre base de données





DROP TABLE PROPRIETAIRES CASCADE CONSTRAINTS;
DROP TABLE CLIENTS CASCADE CONSTRAINTS;
DROP TABLE LOGEMENTS CASCADE CONSTRAINTS;
DROP TABLE PUBLICATIONS CASCADE CONSTRAINTS;
DROP TABLE INTERETS CASCADE CONSTRAINTS;
DROP TABLE RENDEZ_VOUS CASCADE CONSTRAINTS;
DROP TABLE VILLES CASCADE CONSTRAINTS;
DROP TABLE QUARTIERS CASCADE CONSTRAINTS;


COMMIT;

