ALTER TABLE PUBLICATIONS
ADD
CONSTRAINT pub_fk
FOREIGN KEY (id_Mlocation)
REFERENCES MAISONS_LOCATIONS (id_Mlocation);

ALTER TABLE PUBLICATIONS
ADD
FOREIGN KEY (id_Mvente)
REFERENCES MAISONS_VENTES (id_Mvente);