ALTER TABLE RESERVATIONS
ADD 
FOREIGN KEY (id_client)
REFERENCES CLIENTS (id_client) NOVALIDATE;

ALTER TABLE RESERVATIONS
ADD 
FOREIGN KEY (id_Mlocation)
REFERENCES MAISONS_LOCATIONS (id_Mlocation) NOVALIDATE;