ALTER TABLE RESERVATIONS
ADD
CONSTRAINT reservation_pk_1 
FOREIGN KEY (id_client)
REFERENCES CLIENTS (id_client);

ALTER TABLE RESERVATIONS
ADD 
CONSTRAINT reservation_pk_2
FOREIGN KEY (id_Mlocation)
REFERENCES MAISONS_LOCATIONS (id_Mlocation);