ALTER TABLE HISTORIQUES_MVENTES
ADD 
CONSTRAINT histo_vente_pk1
FOREIGN KEY (id_client)
REFERENCES CLIENTS (id_client);


ALTER TABLE HISTORIQUES_MVENTES
ADD 
CONSTRAINT histo_vente_pk2
FOREIGN KEY (id_Mvente)
REFERENCES MAISONS_VENTES(id_Mvente) NOVALIDATE;