CREATE TABLE GEO_LOCALISATION(
    id_Geolocalisation VARCHAR2(9) NOT NULL,
    ville VARCHAR2(30) NOT NULL,
    rue VARCHAR2(20) NOT NULL,
    code_postal VARCHAR2(20) NOT NULL,
    id_Mlocation VARCHAR2(9) NOT NULL,
    id_Mvente VARCHAR2(9) NOT NULL
);