PROMPT *********************************** CLIENTS *************************************************************

INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (100, 'Han', 'mohamed', 'mohamedhan@gmail.com', 677345607, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (101, 'OUM', 'rosine', 'rosine52oum@gmail.com', 697581256, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (102, 'EBI', 'claude', 'claudeebi69@gmail.com', 656894511, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (103, 'FOMOU', 'jospin', 'jospinfomou357@gmail.com', 666251818, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (104, 'LEWE', 'wilfried', 'wilfried523lewe@gmail.com', 676083828, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (105, 'KAMSU', 'joanna', 'kamsujoanna@gmail.com', 676345607, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (107, 'FOKOU', 'chris', 'chrisfokou25@gmail.com', 692451100, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (108, 'MOUKOKO', 'pierette', 'pierettemoukoko@gmail.com', 652211447, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (109, 'TEKOU', 'francis', 'tekou75francis@gmail.com', 677254748 , '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (110, 'BABA', 'Ali', 'alibaba40@gmail.com', 698255624, '120 BP Douala','MLAP9');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (111, 'DJAFA', 'michelle', 'michoudjafa@gmail.com', 654566332, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (112, 'ESSONO', 'junior', 'junioressono@gmail.com', 698565412, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (113, 'ENGA', 'christelle', 'christelle02enga@gmail.com', 665457811, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (114, 'KWETCHE', 'justine', 'kwecthe29justine@gmail.com', 655369639, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (115, 'NONO', 'cabrelle', 'cabrellenono@gmail.com', 655214579, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (116, 'KENFACK', 'pauline', 'paulinekenfack@gmail.com', 698131314, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (117, 'FOCHIE', 'landry', 'landryfochie15@gmail.com', 673568989, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (118, 'SILHA', 'jason', 'jay2003silha@gmail.com', 653565213, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (119, 'FOTSO', 'jack', 'fotso58jacky@gmail.com', 671457896, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (120, 'BIELEU', 'eliette', 'bielieeli95@gmail.com',687868582, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (121, 'MANDENG', 'job', 'jobimandeng@gmail.com', 675698745, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (122, 'NKOT', 'marie', 'marienkot70@gmail.com', 682782245, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (123, 'NGO BOUM', 'tania', 'nb54tania@gmail.com', 656897841, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (124, 'MESSI', 'leonel', 'leomessi10@gmail.com', 656845236, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (125, 'NANI', 'alan', 'nanialan25@gmail.com', 689988778, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (126, 'TCHOUNKEU', 'ralph', 'tchounkeuralph03@gmail.com', 652871526, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (127, 'WANDJI', 'ghislain', 'ghislain33wandji@gmail.com', 655224565, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (128, 'TANKO', 'lalou', 'tankolalou589@gmail.com', 686451523, '120 BP Douala','MLST2');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (129, 'ATSANGUE', 'daryl', 'daryl1478atsangue@gmail.com', 687123525, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (130, 'DOUMBE', 'calixte', 'calixte25doum@gmail.com', 665544665, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (131, 'KOLLO', 'rebecca', 'k12reb@gmail.com', 671256325, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (132, 'MANGA', 'lydie', 'lydiemanga04@gmail.com', 656698742, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (133, 'MIMB', 'loic', 'mimbloic59@gmail.com', 691658324, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (134, 'NIKI', 'alice', 'alice0kiki@gmail.com', 670006523, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (135, 'BAKI', 'daniel', 'bakidan87@gmail.com', 677345711, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (136, 'TSAFACK', 'evana', 'tsafackeva@gmail.com', 677751489, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (137, 'MEYONG', 'patricia', 'patymeyong@gmail.com', 697787554, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (138, 'BABOU', 'francine', 'francinebabe15@gmail.com', 662121545, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (139, 'BAHA', 'patrick', 'bahapat11@gmail.com', 656961427, '120 BP Douala', );
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (140, 'TEDO', 'fabrice', 'tedfabrice@gmail.com', 691541554, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (141, 'SAN', 'evarice', 'sanevarice652@gmail.com', 698899889, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (142, 'DADJI', 'franck', 'franckdadj00@gmail.com', 672558496, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (143, 'AWOU', 'charline', 'awoucharlie999@gmail.com', 691000212, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (144, 'KAYOU', 'james', 'jamek125@gmail.com', 686487542, '120 BP Douala', 'MVST15');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (145, 'NJOYA', 'Ali', 'njoyali456@gmail.com', 694255713, '120 BP Douala', 'MVST10');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (146, 'RAYE', 'hanie', 'rhanie11@gmail.com', 669392919, '120 BP Douala', 'MVST11');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (147, 'MONTANA', 'hannah', 'hannahmontana19@gmail.com', 678115544, '120 BP Douala', 'MLAP1');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (148, 'HADJOU', 'hanick', 'hadj15hanick@gmail.com', 699841568, '120 BP Douala', 'MVCH4');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (149, 'MOUOFO', 'hank', 'mouofohank13@gmail.com', 678182526, '120 BP Douala','MVCH5');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (150, 'JIDJOU', 'hans', 'jid78hans@gmail.com', 664520910, '120 BP Douala', 'MVCH6');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (151, 'DADJEU', 'amelina', 'amedadj60@gmail.com', 692065471, '120 BP Douala', 'MVCH7');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (152, 'EBANG', 'esther', 'estherebang12@gmail.com', 665121514, '120 BP Douala', 'MVCH10');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (153, 'ABADA', 'marine', 'marineabada26@gmail.com', 675871021, '120 BP Douala', 'MVCH11');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (154, 'DOGMO', 'junior', 'juniordogmo@gmail.com', 677457869, '120 BP Douala', 'MLAP9');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (155, 'NOUBISSI', 'nathan', 'noubissinathan02@gmail.com', 694587911, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (156, 'NGNITEN', 'luc', 'ngintenluc22@gmail.com', 699265423, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (157, 'KWELLE', 'noel', 'noelk789@gmail.com', 666121215, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (158, 'PONDI', 'lewis', 'pondilewis15@gmail.com', 677111111, 'Rue 1245  BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, email_client, tel_client, cp_client) VALUES (159, 'DEJONG', 'luis', 'luisdej21@gmail.com', 654891125,'132 BP yaounde');