PROMPT *********************************** CLIENTS *************************************************************

INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (100, 'Han', 'mohamed', 677345607, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (101, 'OUM', 'rosine', 697581256, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (102, 'EBI', 'claude', 656894511, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (103, 'FOMOU', 'jospin', 666251818, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (104, 'LEWE', 'wilfried', 676083828, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (105, 'KAMSU', 'joanna', 676345607, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (107, 'FOKOU', 'chris', '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (108, 'MOUKOKO', 'pierette', 652211447, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (109, 'TEKOU', 'francis', 677254748 , '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (110, 'BABA', 'Ali', 698255624 '120 BP Douala','MLAP9');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (111, 'DJAFA', 'michelle', 654566332, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (112, 'ESSONO', 'junior', 698565412, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (113, 'ENGA', 'christelle', 665457811, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (114, 'KWETCHE', 'justine', 655369639, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (115, 'NONO', 'cabrelle', 655214579, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (116, 'KENFACK', 'pauline', 698131314, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (117, 'FOCHIE', 'landry', 673568989, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (118, 'SILHA', 'jason', 653565213, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (119, 'FOTSO', 'jack', 671457896, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (120, 'BIELEU', 'eliette',687868582, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (121, 'MANDENG', 'job', 675698745, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (122, 'NKOT', 'marie', 682782245, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (123, 'NGO BOUM', 'tania', 656897841, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (124, 'MESSI', 'leonel', 656845236, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (125, 'NANI', 'alan', 689988778, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (126, 'TCHOUNKEU', 'ralph', 652871526, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (127, 'WANDJI', 'ghislain', 655224565, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (128, 'TANKO', 'lalou', 686451523, '120 BP Douala','MLST2');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (129, 'ATSANGUE', 'daryl', 687123525, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (130, 'DOUMBE', 'calixte', 665544665, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (131, 'KOLLO', 'rebecca', 671256325, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (132, 'MANGA', 'lydie', 656698742, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (133, 'MIMB', 'loic', 691658324, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (134, 'NIKI', 'alice', 670006523, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (135, 'BAKI', 'daniel', 677345711, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (136, 'TSAFACK', 'evana', 677751489, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (137, 'MEYONG', 'patricia', 697787554, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (138, 'BABOU', 'francine', 662121545, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (139, 'BAHA', 'patrick', 656961427, '120 BP Douala', );
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (140, 'TEDO', 'fabrice', 691541554, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (141, 'SAN', 'evarice', 698899889, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (142, 'DADJI', 'franck', 672558496, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (143, 'AWOU', 'charline', 691000212, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (144, 'KAYOU', 'james', 686487542, '120 BP Douala', 'MVST15');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (145, 'NJOYA', 'Ali', 694255713, '120 BP Douala', 'MVST10');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (146, 'RAYE', 'hanie', 669392919, '120 BP Douala', 'MVST11');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (147, 'MONTANA', 'hannah', 678115544, '120 BP Douala', 'MLAP1');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (148, 'HADJOU', 'hanick', 699841568, '120 BP Douala', 'MVCH4');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (149, 'MOUOFO', 'hank', 678182526, '120 BP Douala','MVCH5');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (150, 'JIDJOU', 'hans', 664520910, '120 BP Douala', 'MVCH6');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (151, 'DADJEU', 'amelina', 692065471, '120 BP Douala', 'MVCH7');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (152, 'EBANG', 'esther', 665121514, '120 BP Douala', 'MVCH10');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (153, 'ABADA', 'marine', 675871021, '120 BP Douala', 'MVCH11');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (154, 'DOGMO', 'junior', 677457869, '120 BP Douala', 'MLAP9');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (155, 'NOUBISSI', 'nathan', 694587911, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (156, 'NGNITEN', 'luc', 699265423, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (157, 'KWELLE', 'noel', 666121215, '120 BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (158, 'PONDI', 'lewis', 677111111, 'Rue 1245  BP Douala');
INSERT INTO clients (id_client, nom_client, prenom_client, tel_client, mot_passe, est_actif, est_admin) VALUES (159, 'DEJONG', 'luis', 654891125,'132 BP yaounde');