rem Insertion des données dans la table proprietaires

prompt ****************** tables proprietaires *******************

INSERT INTO proprietaires (nom_proprietaire, prenom_proprietaire, email_proprietaire, tel_proprietaire, cp_proprietaire, mot_de_passe_proprietaire, est_actif) VALUES ('KAMGA', 'nealson', 'nealsonkamga2000@gmail.com', '696542412', '12456 BP Ebolowa', 'mot de passe', 'Y');
INSERT INTO proprietaires (nom_proprietaire, prenom_proprietaire, email_proprietaire, tel_proprietaire, cp_proprietaire, mot_de_passe_proprietaire, est_actif) VALUES ('NONO', 'andre', 'nonoandre1998@gmail.com', '665451425', '456 BP Maroua', 'mot de passe', 'Y');
INSERT INTO proprietaires (nom_proprietaire, prenom_proprietaire, email_proprietaire, tel_proprietaire, cp_proprietaire, mot_de_passe_proprietaire, est_actif) VALUES ('SIANOU', 'steve', 'stevesianou2002@gmail.com', '696254535', '852 BP Buea', 'mot de passe', 'Y');
INSERT INTO proprietaires (nom_proprietaire, prenom_proprietaire, email_proprietaire, tel_proprietaire, cp_proprietaire, mot_de_passe_proprietaire, est_actif) VALUES ('FOTSO', 'manuel', 'manuelfotso98@gmail.com', '698255665', '1245 BP Bamenda', 'mot de passe', 'Y');
INSERT INTO proprietaires (nom_proprietaire, prenom_proprietaire, email_proprietaire, tel_proprietaire, cp_proprietaire, mot_de_passe_proprietaire, est_actif) VALUES ('TATCHIE', 'jordan', 'tatchiejordan75@gmail.com', '658789663', '124 BP Garoua', 'mot de passe', 'Y');
INSERT INTO proprietaires (nom_proprietaire, prenom_proprietaire, email_proprietaire, tel_proprietaire, cp_proprietaire, mot_de_passe_proprietaire, est_actif) VALUES ('BANO', 'bernadette', 'banobernadette06@gmail.com', '674562548', '333 BP Bafoussam', 'mot de passe', 'Y');
INSERT INTO proprietaires (nom_proprietaire, prenom_proprietaire, email_proprietaire, tel_proprietaire, cp_proprietaire, mot_de_passe_proprietaire, est_actif) VALUES ('TCHANTCHOU', 'jordan', 'tchantchoujordan@gmail.com', '666124512', '222 BP Bertoua', 'mot de passe', 'Y');
INSERT INTO proprietaires (nom_proprietaire, prenom_proprietaire, email_proprietaire, tel_proprietaire, cp_proprietaire, mot_de_passe_proprietaire, est_actif) VALUES ('ZEBAZE', 'ryan', 'zebaze10ryan@gmail.com', '651232545', '456 BP Douala', 'mot de passe', 'Y');
INSERT INTO proprietaires (nom_proprietaire, prenom_proprietaire, email_proprietaire, tel_proprietaire, cp_proprietaire, mot_de_passe_proprietaire, est_actif) VALUES ('KEGNE', 'johan', 'johankegni01@gmail.com', '666121415', '852 BP Edea', 'mot de passe', 'Y');
INSERT INTO proprietaires (nom_proprietaire, prenom_proprietaire, email_proprietaire, tel_proprietaire, cp_proprietaire, mot_de_passe_proprietaire, est_actif) VALUES ('KOUOTOU', 'jeannette', 'jeanettekouotou33@gmail.com', '678988987', '125896 BP yaounde', 'mot de passe', 'Y');
INSERT INTO proprietaires (nom_proprietaire, prenom_proprietaire, email_proprietaire, tel_proprietaire, cp_proprietaire, mot_de_passe_proprietaire, est_actif) VALUES ('KAMENI', 'borel', 'kameniborel@gmail.com', '695484565', '114 BP Bamenda', 'mot de passe', 'Y');
INSERT INTO proprietaires (nom_proprietaire, prenom_proprietaire, email_proprietaire, tel_proprietaire, cp_proprietaire, mot_de_passe_proprietaire, est_actif) VALUES ('POKEM', 'maxime', 'pokemmax58@gmail.com', '685522332', '185 BP Ebolowa', 'mot de passe', 'Y');
INSERT INTO proprietaires (nom_proprietaire, prenom_proprietaire, email_proprietaire, tel_proprietaire, cp_proprietaire, mot_de_passe_proprietaire, est_actif) VALUES ('NJAHA', 'nathan', 'nathannjaha25@gmail.com', '697755112', '1548 BP yaounde', 'mot de passe', 'Y');
INSERT INTO proprietaires (nom_proprietaire, prenom_proprietaire, email_proprietaire, tel_proprietaire, cp_proprietaire, mot_de_passe_proprietaire, est_actif) VALUES ('FOKOU', 'christine', 'christinefokou@gmail.com', '655211636', '45896 BP Maroua', 'mot de passe', 'Y');
INSERT INTO proprietaires (nom_proprietaire, prenom_proprietaire, email_proprietaire, tel_proprietaire, cp_proprietaire, mot_de_passe_proprietaire, est_actif) VALUES ('TCHINDA', 'yvana', 'tchindayvana@gmail.com', '696255822', '56 BP Edea', 'mot de passe', 'Y');
INSERT INTO proprietaires (nom_proprietaire, prenom_proprietaire, email_proprietaire, tel_proprietaire, cp_proprietaire, mot_de_passe_proprietaire, est_actif) VALUES ('PEUGHOUIA', 'fred', 'fredpeughouia213@gmail.com', '678124657', '46 BP Garoua', 'mot de passe', 'Y');
INSERT INTO proprietaires (nom_proprietaire, prenom_proprietaire, email_proprietaire, tel_proprietaire, cp_proprietaire, mot_de_passe_proprietaire, est_actif) VALUES ('MBAH', 'jenny', 'mbahjenny@gmail.com', '686585741', '568 BP Buea', 'mot de passe', 'Y');
INSERT INTO proprietaires (nom_proprietaire, prenom_proprietaire, email_proprietaire, tel_proprietaire, cp_proprietaire, mot_de_passe_proprietaire, est_actif) VALUES ('POUANI', 'justin', 'pouanijustin@gmail.com', '684562354', '1278 BP Bertoua', 'mot de passe', 'Y');
INSERT INTO proprietaires (nom_proprietaire, prenom_proprietaire, email_proprietaire, tel_proprietaire, cp_proprietaire, mot_de_passe_proprietaire, est_actif) VALUES ('DJOUDA', 'patrick', 'patrickdjouda67@gmail.com', '694121358', '12 BP Douala', 'mot de passe', 'Y');
INSERT INTO proprietaires (nom_proprietaire, prenom_proprietaire, email_proprietaire, tel_proprietaire, cp_proprietaire, mot_de_passe_proprietaire, est_actif) VALUES ('MAKOLO', 'megane', 'makolomegane01@gmail.com', '686451232', '125 BP Bafoussam', 'mot de passe', 'Y');
INSERT INTO proprietaires (nom_proprietaire, prenom_proprietaire, email_proprietaire, tel_proprietaire, cp_proprietaire, mot_de_passe_proprietaire, est_actif) VALUES ('MALENG', 'Sala', 'malengSala01@gmail.com', '686445232', '132 BP Bafoussam', 'mot de passe', 'Y');

