 PROMPT ********************************* TABLE MAISONS_LOCATION **********************************************
 
INSERT INTO MAISONS_LOCATIONS (id_Mlocation, type_location, description_location, adresse_location, prix_menstruel, caution, id_proprietaire) VALUES('MLAP1','appartement','2-chambres2-1-douche-1cuisinesmodernes_meubles-1-balcons ', 'KOTTO',155000,150000,1000);
INSERT INTO MAISONS_LOCATIONS (id_Mlocation, type_location, description_location, adresse_location, prix_menstruel, caution, id_proprietaire) VALUES('MLAP2','appartement','2-chambres2-1-douche-1cuisinesmodernes_meubles-1-balcons ','DAMAS',175000,175000,1001);
INSERT INTO MAISONS_LOCATIONS (id_Mlocation, type_location, description_location, adresse_location, prix_menstruel, caution, id_proprietaire) VALUES('MLAP3','appartement','2-chambres2-1-douche-1cuisinesmodernes_meubles-1-balcons-piscine ', 'KOTTO',199000,155000,1002);
INSERT INTO MAISONS_LOCATIONS (id_Mlocation, type_location, description_location, adresse_location, prix_menstruel, caution, id_proprietaire) VALUES('MLAP4','appartement','2-chambres2-1-douche-1cuisinesmodernes_meubles-1-balcons ', 'DAMAS',2000000,155000,1003);
INSERT INTO MAISONS_LOCATIONS (id_Mlocation, type_location, description_location, adresse_location, prix_menstruel, caution, id_proprietaire) VALUES('MLAP5','appartement','3-chambres2-2-douches-1cuisinesmodernes_meubles-1-balcons','BONANJO',150000,155000,1004);
INSERT INTO MAISONS_LOCATIONS (id_Mlocation, type_location, description_location, adresse_location, prix_menstruel, caution, id_proprietaire) VALUES('MLAP6','appartement','2-chambres2-2-douches-1cuisinesmodernes_meubles-1-balcons-un espase-1-parking ', 'LENDI',20000000,155000,1005);
INSERT INTO MAISONS_LOCATIONS (id_Mlocation, type_location, description_location, adresse_location, prix_menstruel, caution, id_proprietaire) VALUES('MLAP7','appartement','2-chambres2-1-douche-1cuisinesmodernes_meubles-1-balcons ', 'LOGBESSOU',190000,155000,1006);
INSERT INTO MAISONS_LOCATIONS (id_Mlocation, type_location, description_location, adresse_location, prix_menstruel, caution, id_proprietaire) VALUES('MLAP8','appartemente','3-chambres2-2-douches-1cuisinesmodernes_meubles-1-balcons','KOTTO',150000,200000,1007);
INSERT INTO MAISONS_LOCATIONS (id_Mlocation, type_location, description_location, adresse_location, prix_menstruel, caution, id_proprietaire) VALUES('MLST1','studio','1-chambres-1-douche-1cuisinesmodernes_meubles-1-balcons-1-parking ', 'LENDI',15000,155000,1007);
INSERT INTO MAISONS_LOCATIONS (id_Mlocation, type_location, description_location, adresse_location, prix_menstruel, caution, id_proprietaire) VALUES('MLAP9','appartement','2-chambres2-1-douche-1cuisinesmodernes_meubles-1-balcons ', 'BONAMUOSSADI',150000,155000,1008);
INSERT INTO MAISONS_LOCATIONS (id_Mlocation, type_location, description_location, adresse_location, prix_menstruel, caution, id_proprietaire) VALUES('MLAP10','appartement','4-chambres2-3-douche-1cuisinesmodernes_meubles-1-balcons ','BASTOS',150000,155000,1009);
INSERT INTO MAISONS_LOCATIONS (id_Mlocation, type_location, description_location, adresse_location, prix_menstruel, caution, id_proprietaire) VALUES('MLAP12','appartement','2-chambres2-2-douches-1cuisinesmodernes_meubles-1-balcons', '18',150000,155000,1010);
INSERT INTO MAISONS_LOCATIONS (id_Mlocation, type_location, description_location, adresse_location, prix_menstruel, caution, id_proprietaire) VALUES('MLAP13','appartement','2-chambres2-1-douche-1cuisinesmodernes_meubles-1-balcons ','LOGBESSOU',150000,155000,1011);
INSERT INTO MAISONS_LOCATIONS (id_Mlocation, type_location, description_location, adresse_location, prix_menstruel, caution, id_proprietaire) VALUES('MLAP14','appartement','2-chambres2-1-douche-1cuisinesmodernes_meubles-1-balcons ', 'LOGBESSOU',150000,155000,1012);
INSERT INTO MAISONS_LOCATIONS (id_Mlocation, type_location, description_location, adresse_location, prix_menstruel, caution, id_proprietaire) VALUES('MVLA1','villa','4-chambres2 1-douche 1-0cuisinesmodernes_meubles 1-balcons 1-parking', '21',150000,155000,1013);
INSERT INTO MAISONS_LOCATIONS (id_Mlocation, type_location, description_location, adresse_location, prix_menstruel, caution, id_proprietaire) VALUES('MLAP11','appartement','1-chambres 2-douches 1-cuisinesmodernes_meubles 1-balcons ','YABASSI',150000,155000,1014);
INSERT INTO MAISONS_LOCATIONS (id_Mlocation, type_location, description_location, adresse_location, prix_menstruel, caution, id_proprietaire) VALUES('MLCH1','chambre','1-chambres-douche 1-parking','NYALA',15000,155000,1015);
INSERT INTO MAISONS_LOCATIONS (id_Mlocation, type_location, description_location, adresse_location, prix_menstruel, caution, id_proprietaire) VALUES('MLAP15','appartement','2-chambres2 1-douche 1cuisines-modernes_meubles 1-balcons', 'MAKEPE',150000,155000,1016);
INSERT INTO MAISONS_LOCATIONS (id_Mlocation, type_location, description_location, adresse_location, prix_menstruel, caution, id_proprietaire) VALUES('MLAP16','appartement','3-chambres2-1-douche-1cuisinesmodernes_meubles-1-balcons -1-parking', 'LOGPOM',200000,155000,1017);
INSERT INTO MAISONS_LOCATIONS (id_Mlocation, type_location, description_location, adresse_location, prix_menstruel, caution, id_proprietaire) VALUES('MLST2','Studio','1-chambres 1-douches 1cuisinesmodernes_meubles-1-balcons ','DLALOGPOM',35000,155000,1018);
INSERT INTO MAISONS_LOCATIONS (id_Mlocation, type_location, description_location, adresse_location, prix_menstruel, caution, id_proprietaire) VALUES('MLAP17','appartement','2-chambres 2-douches-1cuisinesmodernes_meubles-1-balcons -1-parking', 'DLABASSON',200000,155000,1019);
INSERT INTO MAISONS_LOCATIONS (id_Mlocation, type_location, description_location, adresse_location, prix_menstruel, caution, id_proprietaire) VALUES('MLST3','studio','1-chambres 1-douche 1-cuisinesmodernes_meubles 1-balcons 1-parking piscine ', 'DLA520',50000,155000,1020);