 PROMPT ********************************* TABLE MAISONS_LOCATION **********************************************
 
INSERT INTO LOGEMENTS (id_logement,  id_proprietaire, id_quartier, type_logement,  Nbre_chambre, Nbre_douche, AvecPiscine, AvecMeuble, AvecBalcon, AvecParking, adresse_logement, prix_mensuel, caution) VALUES('MLAP1',1000, 'LOG1', 'appartement',2, 2, 'N', 'Y', 'Y', 'N', 'KOTTO',155000,150000);
INSERT INTO LOGEMENTS (id_logement,  id_proprietaire, id_quartier, type_logement,  Nbre_chambre, Nbre_douche, AvecPiscine, AvecMeuble, AvecBalcon, AvecParking, adresse_logement, prix_mensuel, caution) VALUES('MLAP2',1001, 'LOG2', 'appartement',3, 2, 'N', 'Y', 'Y', 'N','DAMAS',175000,175000);
INSERT INTO LOGEMENTS (id_logement,  id_proprietaire, id_quartier, type_logement,  Nbre_chambre, Nbre_douche, AvecPiscine, AvecMeuble, AvecBalcon, AvecParking, adresse_logement, prix_mensuel, caution) VALUES('MLAP3',1002, 'LOG3', 'appartement',2,, 'N', 'Y', 'Y', 'N', 'KOTTO',199000,155000);
INSERT INTO LOGEMENTS (id_logement,  id_proprietaire, id_quartier, type_logement,  Nbre_chambre, Nbre_douche, AvecPiscine, AvecMeuble, AvecBalcon, AvecParking, adresse_logement, prix_mensuel, caution) VALUES('MLAP4',1003, 'LOG4', 'appartement',4, 2, 'N', 'Y', 'Y', 'N', 'DAMAS',2000000,155000);
INSERT INTO LOGEMENTS (id_logement,  id_proprietaire, id_quartier, type_logement,  Nbre_chambre, Nbre_douche, AvecPiscine, AvecMeuble, AvecBalcon, AvecParking, adresse_logement, prix_mensuel, caution) VALUES('MLAP5',1004, 'LOG5', 'appartement',2, 2, 'N', 'Y', 'Y', 'N','BONANJO',150000,155000);
INSERT INTO LOGEMENTS (id_logement,  id_proprietaire, id_quartier, type_logement,  Nbre_chambre, Nbre_douche, AvecPiscine, AvecMeuble, AvecBalcon, AvecParking, adresse_logement, prix_mensuel, caution) VALUES('MLAP6',1005, 'LOG6', 'appartement',2, 1, 'N', 'Y', 'Y', 'N', 'LENDI',20000000,155000);
INSERT INTO LOGEMENTS (id_logement,  id_proprietaire, id_quartier, type_logement,  Nbre_chambre, Nbre_douche, AvecPiscine, AvecMeuble, AvecBalcon, AvecParking, adresse_logement, prix_mensuel, caution) VALUES('MLAP7',1006, 'LOG7', 'appartement',3, 3, 'N', 'Y', 'Y', 'N', 'LOGBESSOU',190000,155000);
INSERT INTO LOGEMENTS (id_logement,  id_proprietaire, id_quartier, type_logement,  Nbre_chambre, Nbre_douche, AvecPiscine, AvecMeuble, AvecBalcon, AvecParking, adresse_logement, prix_mensuel, caution) VALUES('MLAP8',1007, 'LOG8', 'appartement',2, 2, 'N', 'Y', 'Y', 'N','KOTTO',150000,200000);
INSERT INTO LOGEMENTS (id_logement,  id_proprietaire, id_quartier, type_logement,  Nbre_chambre, Nbre_douche, AvecPiscine, AvecMeuble, AvecBalcon, AvecParking, adresse_logement, prix_mensuel, caution) VALUES('MLST1',1007, 'LOG9', 'studio',1, 1, 'N', 'Y', 'Y', 'N', 'LENDI',15000,155000);
INSERT INTO LOGEMENTS (id_logement,  id_proprietaire, id_quartier, type_logement,  Nbre_chambre, Nbre_douche, AvecPiscine, AvecMeuble, AvecBalcon, AvecParking, adresse_logement, prix_mensuel, caution) VALUES('MLAP9',1009, 'LOG10', 'appartement',2, 2, 'N', 'Y', 'Y', 'N', 'BONAMUOSSADI',150000,155000);
INSERT INTO LOGEMENTS (id_logement,  id_proprietaire, id_quartier, type_logement,  Nbre_chambre, Nbre_douche, AvecPiscine, AvecMeuble, AvecBalcon, AvecParking, adresse_logement, prix_mensuel, caution) VALUES('MLAP10',1008,'LOG11', 'appartement',2, 2, 'N', 'Y', 'Y', 'N','BASTOS',150000,155000);
INSERT INTO LOGEMENTS (id_logement,  id_proprietaire, id_quartier, type_logement,  Nbre_chambre, Nbre_douche, AvecPiscine, AvecMeuble, AvecBalcon, AvecParking, adresse_logement, prix_mensuel, caution) VALUES('MLAP12',1010,'LOG12', 'appartement',2, 2, 'N', 'Y', 'Y', 'N', '18',150000,155000);
INSERT INTO LOGEMENTS (id_logement,  id_proprietaire, id_quartier, type_logement,  Nbre_chambre, Nbre_douche, AvecPiscine, AvecMeuble, AvecBalcon, AvecParking, adresse_logement, prix_mensuel, caution) VALUES('MLAP13',1011,'LOG13', 'appartement',2, 2, 'N', 'Y', 'Y', 'N','LOGBESSOU',150000,155000);
INSERT INTO LOGEMENTS (id_logement,  id_proprietaire, id_quartier, type_logement,  Nbre_chambre, Nbre_douche, AvecPiscine, AvecMeuble, AvecBalcon, AvecParking, adresse_logement, prix_mensuel, caution) VALUES('MLAP14',1012,'LOG14', 'appartement',2, 2, 'N', 'Y', 'Y', 'N', 'LOGBESSOU',150000,155000);
INSERT INTO LOGEMENTS (id_logement,  id_proprietaire, id_quartier, type_logement,  Nbre_chambre, Nbre_douche, AvecPiscine, AvecMeuble, AvecBalcon, AvecParking, adresse_logement, prix_mensuel, caution) VALUES('MVLA1',1013,'LOG15', 'villa',5, 4, 'N', 'Y', 'Y', 'N', '21',150000,155000);
INSERT INTO LOGEMENTS (id_logement,  id_proprietaire, id_quartier, type_logement,  Nbre_chambre, Nbre_douche, AvecPiscine, AvecMeuble, AvecBalcon, AvecParking, adresse_logement, prix_mensuel, caution) VALUES('MLAP11',1014,'LOG16', 'appartement',2, 2, 'N', 'Y', 'Y', 'N','YABASSI',150000,155000);
INSERT INTO LOGEMENTS (id_logement,  id_proprietaire, id_quartier, type_logement,  Nbre_chambre, Nbre_douche, AvecPiscine, AvecMeuble, AvecBalcon, AvecParking, adresse_logement, prix_mensuel, caution) VALUES('MLCH1',1015,'LOG17', 'chambre',2, 2, 'N', 'Y', 'Y', 'N','NYALA',15000,155000);
INSERT INTO LOGEMENTS (id_logement,  id_proprietaire, id_quartier, type_logement,  Nbre_chambre, Nbre_douche, AvecPiscine, AvecMeuble, AvecBalcon, AvecParking, adresse_logement, prix_mensuel, caution) VALUES('MLAP15',1016,'LOG18', 'appartement',2, 2, 'N', 'Y', 'Y', 'N', 'MAKEPE',150000,155000);
INSERT INTO LOGEMENTS (id_logement,  id_proprietaire, id_quartier, type_logement,  Nbre_chambre, Nbre_douche, AvecPiscine, AvecMeuble, AvecBalcon, AvecParking, adresse_logement, prix_mensuel, caution) VALUES('MLAP16',1017,'LOG19', 'appartement',2, 2, 'N', 'Y', 'Y', 'N', 'LOGPOM',200000,155000);
INSERT INTO LOGEMENTS (id_logement,  id_proprietaire, id_quartier, type_logement,  Nbre_chambre, Nbre_douche, AvecPiscine, AvecMeuble, AvecBalcon, AvecParking, adresse_logement, prix_mensuel, caution) VALUES('MLST2',1018,'LOG20','Studio',1, 1, 'N', 'Y', 'Y', 'N','DLALOGPOM',35000,155000);
INSERT INTO LOGEMENTS (id_logement,  id_proprietaire, id_quartier, type_logement,  Nbre_chambre, Nbre_douche, AvecPiscine, AvecMeuble, AvecBalcon, AvecParking, adresse_logement, prix_mensuel, caution) VALUES('MLAP17',1019,'LOG21', 'appartement',2, 2, 'N', 'Y', 'Y', 'N', 'DLABASSON',200000,155000);
INSERT INTO LOGEMENTS (id_logement,  id_proprietaire, id_quartier, type_logement,  Nbre_chambre, Nbre_douche, AvecPiscine, AvecMeuble, AvecBalcon, AvecParking, adresse_logement, prix_mensuel, caution) VALUES('MLST3',1020,'LOG22', 'studio',1, 1, 'N', 'Y', 'Y', 'N', 'DLA520',50000,155000);
INSERT INTO LOGEMENTS (id_logement,  id_proprietaire, id_quartier, type_logement,  Nbre_chambre, Nbre_douche, AvecPiscine, AvecMeuble, AvecBalcon, AvecParking, adresse_logement, prix_mensuel, caution) VALUES('MLS3',1021,'LOG23', 'appartement',2, 1, 'N', 'Y', 'Y', 'N', 'DLA520',50000,155000);
INSERT INTO LOGEMENTS (id_logement,  id_proprietaire, id_quartier, type_logement,  Nbre_chambre, Nbre_douche, AvecPiscine, AvecMeuble, AvecBalcon, AvecParking, adresse_logement, prix_mensuel, caution) VALUES('MLST5',1022,'LOG24', 'studio',1, 1, 'N', 'Y', 'Y', 'N', 'DLA520',50000,155000);
INSERT INTO LOGEMENTS (id_logement,  id_proprietaire, id_quartier, type_logement,  Nbre_chambre, Nbre_douche, AvecPiscine, AvecMeuble, AvecBalcon, AvecParking, adresse_logement, prix_mensuel, caution) VALUES('MLAP8',1023,'LOG25', 'studio',1, 1, 'N', 'Y', 'Y', 'N', 'DLA520',50000,155000);
INSERT INTO LOGEMENTS (id_logement,  id_proprietaire, id_quartier, type_logement,  Nbre_chambre, Nbre_douche, AvecPiscine, AvecMeuble, AvecBalcon, AvecParking, adresse_logement, prix_mensuel, caution) VALUES('MLST30',1024,'LOG26', 'studio',1, 1, 'N', 'Y', 'Y', 'N', 'DLA520',50000,155000);
INSERT INTO LOGEMENTS (id_logement,  id_proprietaire, id_quartier, type_logement,  Nbre_chambre, Nbre_douche, AvecPiscine, AvecMeuble, AvecBalcon, AvecParking, adresse_logement, prix_mensuel, caution) VALUES('MLS12',1025,'LOG27', 'villa',4, 4, 'Y', 'Y', 'Y', 'N', 'DLA520',50000,155000);
