 PROMPT ********************************* TABLE MAISONS_LOCATION **********************************************
 
INSERT INTO LOGEMENTS (id_logement,  id_proprietaire, id_quartier, id_publication, type_logement, description, adresse_logement, prix_mensuel, caution) VALUES('MLAP1',1000, 'LOG1', 1, 'appartement','2-chambres2-1-douche-1cuisinesmodernes_meubles-1-balcons ', 'KOTTO',155000,150000);
INSERT INTO LOGEMENTS (id_logement,  id_proprietaire, id_quartier, id_publication, type_logement, description, adresse_logement, prix_mensuel, caution) VALUES('MLAP2',1001, 'LOG2', 2, 'appartement','2-chambres2-1-douche-1cuisinesmodernes_meubles-1-balcons ','DAMAS',175000,175000);
INSERT INTO LOGEMENTS (id_logement,  id_proprietaire, id_quartier, id_publication, type_logement, description, adresse_logement, prix_mensuel, caution) VALUES('MLAP3',1002, 'LOG3', 3, 'appartement','2-chambres2-1-douche-1cuisinesmodernes_meubles-1-balcons-piscine ', 'KOTTO',199000,155000);
INSERT INTO LOGEMENTS (id_logement,  id_proprietaire, id_quartier, id_publication, type_logement, description, adresse_logement, prix_mensuel, caution) VALUES('MLAP4',1003, 'LOG4', 4, 'appartement','2-chambres2-1-douche-1cuisinesmodernes_meubles-1-balcons ', 'DAMAS',2000000,155000);
INSERT INTO LOGEMENTS (id_logement,  id_proprietaire, id_quartier, id_publication, type_logement, description, adresse_logement, prix_mensuel, caution) VALUES('MLAP5',1004, 'LOG5', 5, 'appartement','3-chambres2-2-douches-1cuisinesmodernes_meubles-1-balcons','BONANJO',150000,155000);
INSERT INTO LOGEMENTS (id_logement,  id_proprietaire, id_quartier, id_publication, type_logement, description, adresse_logement, prix_mensuel, caution) VALUES('MLAP6',1005, 'LOG6', 6, 'appartement','2-chambres2-2-douches-1cuisinesmodernes_meubles-1-balcons-un espase-1-parking ', 'LENDI',20000000,155000);
INSERT INTO LOGEMENTS (id_logement,  id_proprietaire, id_quartier, id_publication, type_logement, description, adresse_logement, prix_mensuel, caution) VALUES('MLAP7',1006, 'LOG7', 7, 'appartement','2-chambres2-1-douche-1cuisinesmodernes_meubles-1-balcons ', 'LOGBESSOU',190000,155000);
INSERT INTO LOGEMENTS (id_logement,  id_proprietaire, id_quartier, id_publication, type_logement, description, adresse_logement, prix_mensuel, caution) VALUES('MLAP8',1007, 'LOG8', 8, 'appartement','3-chambres2-2-douches-1cuisinesmodernes_meubles-1-balcons','KOTTO',150000,200000);
INSERT INTO LOGEMENTS (id_logement,  id_proprietaire, id_quartier, id_publication, type_logement, description, adresse_logement, prix_mensuel, caution) VALUES('MLST1',1007, 'LOG9', 9, 'studio','1-chambres-1-douche-1cuisinesmodernes_meubles-1-balcons-1-parking ', 'LENDI',15000,155000);
INSERT INTO LOGEMENTS (id_logement,  id_proprietaire, id_quartier, id_publication, type_logement, description, adresse_logement, prix_mensuel, caution) VALUES('MLAP9',1009, 'LOG10',10, 'appartement','2-chambres2-1-douche-1cuisinesmodernes_meubles-1-balcons ', 'BONAMUOSSADI',150000,155000);
INSERT INTO LOGEMENTS (id_logement,  id_proprietaire, id_quartier, id_publication, type_logement, description, adresse_logement, prix_mensuel, caution) VALUES('MLAP10',1008,'LOG11',11, 'appartement','4-chambres2-3-douche-1cuisinesmodernes_meubles-1-balcons ','BASTOS',150000,155000);
INSERT INTO LOGEMENTS (id_logement,  id_proprietaire, id_quartier, id_publication, type_logement, description, adresse_logement, prix_mensuel, caution) VALUES('MLAP12',1010,'LOG12',12, 'appartement','2-chambres2-2-douches-1cuisinesmodernes_meubles-1-balcons', '18',150000,155000);
INSERT INTO LOGEMENTS (id_logement,  id_proprietaire, id_quartier, id_publication, type_logement, description, adresse_logement, prix_mensuel, caution) VALUES('MLAP13',1011,'LOG13',13, 'appartement','2-chambres2-1-douche-1cuisinesmodernes_meubles-1-balcons ','LOGBESSOU',150000,155000);
INSERT INTO LOGEMENTS (id_logement,  id_proprietaire, id_quartier, id_publication, type_logement, description, adresse_logement, prix_mensuel, caution) VALUES('MLAP14',1012,'LOG14',14, 'appartement','2-chambres2-1-douche-1cuisinesmodernes_meubles-1-balcons ', 'LOGBESSOU',150000,155000);
INSERT INTO LOGEMENTS (id_logement,  id_proprietaire, id_quartier, id_publication, type_logement, description, adresse_logement, prix_mensuel, caution) VALUES('MVLA1',1013,'LOG15', 15, 'villa','4-chambres2 1-douche 1-0cuisinesmodernes_meubles 1-balcons 1-parking', '21',150000,155000);
INSERT INTO LOGEMENTS (id_logement,  id_proprietaire, id_quartier, id_publication, type_logement, description, adresse_logement, prix_mensuel, caution) VALUES('MLAP11',1014,'LOG16',16, 'appartement','1-chambres 2-douches 1-cuisinesmodernes_meubles 1-balcons ','YABASSI',150000,155000);
INSERT INTO LOGEMENTS (id_logement,  id_proprietaire, id_quartier, id_publication, type_logement, description, adresse_logement, prix_mensuel, caution) VALUES('MLCH1',1015,'LOG17',17, 'chambre','1-chambres-douche 1-parking','NYALA',15000,155000);
INSERT INTO LOGEMENTS (id_logement,  id_proprietaire, id_quartier, id_publication, type_logement, description, adresse_logement, prix_mensuel, caution) VALUES('MLAP15',1016,'LOG18',18, 'appartement','2-chambres2 1-douche 1cuisines-modernes_meubles 1-balcons', 'MAKEPE',150000,155000);
INSERT INTO LOGEMENTS (id_logement,  id_proprietaire, id_quartier, id_publication, type_logement, description, adresse_logement, prix_mensuel, caution) VALUES('MLAP16',1017,'LOG19',19, 'appartement','3-chambres2-1-douche-1cuisinesmodernes_meubles-1-balcons -1-parking', 'LOGPOM',200000,155000);
INSERT INTO LOGEMENTS (id_logement,  id_proprietaire, id_quartier, id_publication, type_logement, description, adresse_logement, prix_mensuel, caution) VALUES('MLST2',1018,'LOG20', 20,'Studio','1-chambres 1-douches 1cuisinesmodernes_meubles-1-balcons ','DLALOGPOM',35000,155000);
INSERT INTO LOGEMENTS (id_logement,  id_proprietaire, id_quartier, id_publication, type_logement, description, adresse_logement, prix_mensuel, caution) VALUES('MLAP17',1019,'LOG21',21, 'appartement','2-chambres 2-douches-1cuisinesmodernes_meubles-1-balcons -1-parking', 'DLABASSON',200000,155000);
INSERT INTO LOGEMENTS (id_logement,  id_proprietaire, id_quartier, id_publication, type_logement, description, adresse_logement, prix_mensuel, caution) VALUES('MLST3',1020,'LOG22',22, 'studio','1-chambres 1-douche 1-cuisinesmodernes_meubles 1-balcons 1-parking piscine ', 'DLA520',50000,155000);