INSERT INTO QUARTIERS (id_quartier, nom_quartier, id_ville) VALUES ('LOG1', 'Logbessou', 'dla');
INSERT INTO QUARTIERS (id_quartier, nom_quartier, id_ville) VALUES ('LOG2', 'Logbessou', 'dla');
INSERT INTO QUARTIERS (id_quartier, nom_quartier, id_ville) VALUES ('LOG3', 'Logbessou', 'dla');
INSERT INTO QUARTIERS (id_quartier, nom_quartier, id_ville) VALUES ('LOG4',  'Nkotaba', 'ngde');
INSERT INTO QUARTIERS (id_quartier, nom_quartier, id_ville) VALUES ('LOG5',  'Akwa', 'bue');
INSERT INTO QUARTIERS (id_quartier, nom_quartier, id_ville) VALUES ('LOG6',  'mont blanc', 'ebl');
INSERT INTO QUARTIERS (id_quartier, nom_quartier, id_ville) VALUES ('LOG7',  'Carrefour deux poteaux', 'baf');
INSERT INTO QUARTIERS (id_quartier, nom_quartier, id_ville) VALUES ('LOG8',  'Jota', 'yde');
INSERT INTO QUARTIERS (id_quartier, nom_quartier, id_ville) VALUES ('LOG9',  'Bepanda', 'dla');
INSERT INTO QUARTIERS (id_quartier, nom_quartier, id_ville) VALUES ('LOG10',  'Bastoss', 'yde');
INSERT INTO QUARTIERS (id_quartier, nom_quartier, id_ville) VALUES ('LOG11',  'Nkouagele', 'yde');
INSERT INTO QUARTIERS (id_quartier, nom_quartier, id_ville) VALUES ('LOG12',  'rue de la liberté', 'mar');
INSERT INTO QUARTIERS (id_quartier, nom_quartier, id_ville) VALUES ('LOG13',  'Mont blanc', 'yde');
INSERT INTO QUARTIERS (id_quartier, nom_quartier, id_ville) VALUES ('LOG14',  'Nkoa', 'brt');
INSERT INTO QUARTIERS (id_quartier, nom_quartier, id_ville) VALUES ('LOG15',  'Ntabang', 'brt');
INSERT INTO QUARTIERS (id_quartier, nom_quartier, id_ville) VALUES ('LOG16',  'Leste', 'lim');
INSERT INTO QUARTIERS (id_quartier, nom_quartier, id_ville) VALUES ('LOG17',  'Yaoura', 'gar');
INSERT INTO QUARTIERS (id_quartier, nom_quartier, id_ville) VALUES ('LOG18',  'Maru', 'lim');
INSERT INTO QUARTIERS (id_quartier, nom_quartier, id_ville) VALUES ('LOG19',  'Nkotaba', 'gar');
INSERT INTO QUARTIERS (id_quartier, nom_quartier, id_ville) VALUES ('LOG20',  'Cavn', 'lim');
INSERT INTO QUARTIERS (id_quartier, nom_quartier, id_ville) VALUES ('LOG21',  'Yuange', 'gar');
INSERT INTO QUARTIERS (id_quartier, nom_quartier, id_ville) VALUES ('LOG22',  'Nkotaba', 'gar');
INSERT INTO QUARTIERS (id_quartier, nom_quartier, id_ville) VALUES ('LOG23',  'Beddi', 'dla');
INSERT INTO QUARTIERS (id_quartier, nom_quartier, id_ville) VALUES ('LOG24',  'Nsam', 'yde');
INSERT INTO QUARTIERS (id_quartier, nom_quartier, id_ville) VALUES ('LOG25',  'Etoug-ebe', 'yde');
INSERT INTO QUARTIERS (id_quartier, nom_quartier, id_ville) VALUES ('LOG26',  'Kotto', 'dla');
INSERT INTO QUARTIERS (id_quartier, nom_quartier, id_ville) VALUES ('LOG27',  'Makepe', 'dla');
