PROMPT **************** TABLES MAISONS_LOCATION *****************************************************

PRO INSERTING into maisons_location
set define off
begin
   INSERT INTO maisons_location (id_location, type_location, description_location, adresse_location, prix_menstruel, caution, id_proprietaire) VALUES('1me','location de domicile','2-chambres2-1-touches-1cuisinesmodernes_meubles-1-balcons ', 'KOTTO',155000,150000,'1pro');
   INSERT INTO maisons_location (id_location, type_location, description_location, adresse_location, prix_menstruel, caution, id_proprietaire) VALUES('2me','location de domicile','2-chambres2-1-touches-1cuisinesmodernes_meubles-1-balcons ','DAMAS',175000,175000,'2pro');
   INSERT INTO maisons_location (id_location, type_location, description_location, adresse_location, prix_menstruel, caution, id_proprietaire) VALUES('3me','location de domicile','2-chambres2-1-touches-1cuisinesmodernes_meubles-1-balcons-piscine ', 'KOTTO',199000,155000,190000,'3pro');
   INSERT INTO maisons_location (id_location, type_location, description_location, adresse_location, prix_menstruel, caution, id_proprietaire) VALUES('4me','location de domicile','2-chambres2-1-touches-1cuisinesmodernes_meubles-1-balcons ', 'DAMAS',2000000,155000,'4pro');
   INSERT INTO maisons_location (id_location, type_location, description_location, adresse_location, prix_menstruel, caution, id_proprietaire) VALUES('5me','location de domicile','3-chambres2-2-touches-1cuisinesmodernes_meubles-1-balcons','BONANJO',150000,155000,'5pro');
   INSERT INTO maisons_location (id_location, type_location, description_location, adresse_location, prix_menstruel, caution, id_proprietaire) VALUES('6me','location de domicile','2-chambres2-2-touches-1cuisinesmodernes_meubles-1-balcons-un espase-1-parking ', 'LENDI',20000000,155000,'6pro');
   INSERT INTO maisons_location (id_location, type_location, description_location, adresse_location, prix_menstruel, caution, id_proprietaire) VALUES('7me','location de domicile','2-chambres2-1-touches-1cuisinesmodernes_meubles-1-balcons ', 'LOGBESSOU',190000,155000,'7pro');
   INSERT INTO maisons_location (id_location, type_location, description_location, adresse_location, prix_menstruel, caution, id_proprietaire) VALUES('8me','location de domicile','3-chambres2-2-touches-1cuisinesmodernes_meubles-1-balcons','KOTTO',150000,'1po',200000,155000,'8pro');
   INSERT INTO maisons_location (id_location, type_location, description_location, adresse_location, prix_menstruel, caution, id_proprietaire) VALUES('9me','location de domicile','2-chambres2-1-touches-1cuisinesmodernes_meubles-1-balcons-1-parking ', 'LENDI',150000,155000,'9pro');
   INSERT INTO maisons_location (id_location, type_location, description_location, adresse_location, prix_menstruel, caution, id_proprietaire) VALUES('10me','location de domicile','2-chambres2-1-touches-1cuisinesmodernes_meubles-1-balcons ', 'BONAMUOSSADI',150000,155000,'10pro');
   INSERT INTO maisons_location (id_location, type_location, description_location, adresse_location, prix_menstruel, caution, id_proprietaire) VALUES('11me','location de domicile','4-chambres2-3-touches-1cuisinesmodernes_meubles-1-balcons ','BASTOS',150000,155000,'11pro');
   INSERT INTO maisons_location (id_location, type_location, description_location, adresse_location, prix_menstruel, caution, id_proprietaire) VALUES('12me','location de domicile','2-chambres2-2-touches-1cuisinesmodernes_meubles-1-balcons-1-parking ', '14',150000,155000,'12pro');
   INSERT INTO maisons_location (id_location, type_location, description_location, adresse_location, prix_menstruel, caution, id_proprietaire) VALUES('13me','location de domicile','2-chambres2-2-touches-1cuisinesmodernes_meubles-1-balcons', '18',150000,155000,'13pro');
   INSERT INTO maisons_location (id_location, type_location, description_location, adresse_location, prix_menstruel, caution, id_proprietaire) VALUES('14me','location de domicile','2-chambres2-1-touches-1cuisinesmodernes_meubles-1-balcons ','LOGBESSOU',150000,155000,'14pro');
   INSERT INTO maisons_location (id_location, type_location, description_location, adresse_location, prix_menstruel, caution, id_proprietaire) VALUES('15me','location de domicile','2-chambres2-1-touches-1cuisinesmodernes_meubles-1-balcons ', 'LOGBESSOU',150000,155000,'15pro');
   INSERT INTO maisons_location (id_location, type_location, description_location, adresse_location, prix_menstruel, caution, id_proprietaire) VALUES('16me','location de domicile','4-chambres2-1-touches-1cuisinesmodernes_meubles-1-balcons-1-parking', '21',150000,155000,'16pro');
   INSERT INTO maisons_location (id_location, type_location, description_location, adresse_location, prix_menstruel, caution, id_proprietaire) VALUES('17me','location de domicile','1-chambres2-2-touches-1cuisinesmodernes_meubles-1-balcons ','YABASSI',150000,155000,'17pro');
   INSERT INTO maisons_location (id_location, type_location, description_location, adresse_location, prix_menstruel, caution, id_proprietaire) VALUES('18me','location de domicile','2-chambres2-2-touches-1cuisinesmodernes_meubles-1-balcons-1-parking ', 'NYALA',150000,155000,'18pro');
   INSERT INTO maisons_location (id_location, type_location, description_location, adresse_location, prix_menstruel, caution, id_proprietaire) VALUES('19me','location de domicile','2-chambres2-1-touches-1cuisinesmodernes_meubles-1-balcons', 'MAKEPE',150000,155000,'19pro');
   INSERT INTO maisons_location (id_location, type_location, description_location, adresse_location, prix_menstruel, caution, id_proprietaire) VALUES('20me','location de domicile','3-chambres2-1-touches-1cuisinesmodernes_meubles-1-balcons -1-parking', 'LOGPOM',200000,155000,'20pro');
   INSERT INTO maisons_location (id_location, type_location, description_location, adresse_location, prix_menstruel, caution, id_proprietaire) VALUES('21me','location de domicile','2-chambres2-2-touches-1cuisinesmodernes_meubles-1-balcons ','LOGPOM',150000,'1po',150000,155000,'21pro');
   INSERT INTO maisons_location (id_location, type_location, description_location, adresse_location, prix_menstruel, caution, id_proprietaire) VALUES('22me','location de domicile','2-chambres2-2-touches-1cuisinesmodernes_meubles-1-balcons -1-parking', 'BASSON',200000,155000,'22pro');
   INSERT INTO maisons_location (id_location, type_location, description_location, adresse_location, prix_menstruel, caution, id_proprietaire) VALUES('23me','location de domicile','2-chambres2-1-touches-1cuisinesmodernes_meubles-1-balcons-1-parking-piscine ', 'DEIDO',150000,155000,'23po');
end