rem Insertion des données dans la table clients
PROMPT **************** TABLES MAISONS_VENTE ***********************************

INSERT INTO maisons_vente (id_vente, type_vente, description_vente, adresse_vente, prix_vente,id_client) VALUES('MVCH201','chambres','2-chambres 2-douches-1cuisinesmodernes_meubles-1-balcons ', 'DLAKOTTO26',1000000000, 100);
INSERT INTO maisons_vente (id_vente, type_vente, description_vente, adresse_vente, prix_vente,id_client) VALUES('MVH201','immeuble','3-chambres 3-douches-1cuisinesmodernes_meubles-1-balcons ', 'DLAKOTTO27',100000000,101);
INSERT INTO maisons_vente (id_vente, type_vente, description_vente, adresse_vente, prix_vente,id_client) VALUES('MVCH211','immeuble','2-chambres 1-douche-1cuisinesmodernes_meubles-1-balcons-1-grand couloir-1-grande piscine-1-grand espacejardinage  ', 'DLAKWA257',250000000,102);
INSERT INTO maisons_vente (id_vente, type_vente, description_vente, adresse_vente, prix_vente,id_client) VALUES('MVCH211','DUPLEX','2-chambres1-douche-1cuisinesmodernes_meubles-1-balcons-1-grande piscine', 'LENDI', 103);
INSERT INTO maisons_vente (id_vente, type_vente, description_vente, adresse_vente, prix_vente,id_client) VALUES('MVAP2'  , 'DUPLEX ',' 4-chambres 2-douches-1cuisinesmodernes_meubles-1-balcons1-grand couloir1-grand espacejardinage-1-grande cour ', 'DLABONAMOUSSADI26',1000000000, 104);
INSERT INTO maisons_vente (id_vente, type_vente, description_vente, adresse_vente, prix_vente,id_client) VALUES('MVD201','maison',' 4-chambres 2-douches-1cuisinesmodernes_meubles-2-balcons1-grande cour1-grande piscine ', 'DLALOGBESSOU237',30000000,105);
INSERT INTO maisons_vente (id_vente, type_vente, description_vente, adresse_vente, prix_vente,id_client) VALUES('MVH2','immeuble','3-chambres 2-douches-1cuisinesmodernes_meubles-2-balcons1-grande cour1-grande piscine ', 'DLABASSON267',20000000,106);
INSERT INTO maisons_vente (id_vente, type_vente, description_vente, adresse_vente, prix_vente,id_client) VALUES('MVH22','DUPLEX ',' 4-chambres2-douches-1cuisinesmodernes_meubles-2-balcons1-grande cour ', 'DLA14',25000000, 107);
INSERT INTO maisons_vente (id_vente, type_vente, description_vente, adresse_vente, prix_vente,id_client) VALUES('MVCH1','maison','3-chambres 3-douches-1cuisinesmodernes_meubles-1-balcons ', 'DLAKOTTO8',150000000,108);
INSERT INTO maisons_vente (id_vente, type_vente, description_vente, adresse_vente, prix_vente,id_client) VALUES('MVCH2','villa','2-chambres 2-douches-1cuisinesmodernes_meubles-1 balcons ', 'DLABONANJO87',1000000000, 109);
INSERT INTO maisons_vente (id_vente, type_vente, description_vente, adresse_vente, prix_vente,id_client) VALUES('MVST15','villa','2-chambres 2-douches-1cuisinesmodernes_meubles-1 balcons', 'DLABONANJO88',1000000000,1010, 110);
INSERT INTO maisons_vente (id_vente, type_vente, description_vente, adresse_vente, prix_vente,id_client) VALUES('MVST10','DUPLEX ',' 4-chambres2-douches-1cuisinesmodernes_meubles-1-balcons1-grand couloir1-grand espacejardinage-1-grande cour ', 'YDEBASTOS27',1000000000,111);
INSERT INTO maisons_vente (id_vente, type_vente, description_vente, adresse_vente, prix_vente,id_client) VALUES('MVCH20','villa','4-chambres 2-douches-1cuisinesmodernes_meubles-1-balcons1-grand couloir1-grand espacejardinage-1-grande cour ', 'YDEDAMAS5',12000000, 112);
INSERT INTO maisons_vente (id_vente, type_vente, description_vente, adresse_vente, prix_vente,d_client) VALUES('MVSH2','immeuble' ,' 2-chambres 1-douche-1cuisinesmodernes_meubles-1-balcons-1-grand couloir-1-grande piscine-1-grand espacejardinage  ', 'DLAKWA8',50000000, 113);
INSERT INTO maisons_vente (id_vente, type_vente, description_vente, adresse_vente, prix_vente,id_client) VALUES('MVAP3','DUPLEX ','2-chambres 1-douche-1cuisinesmodernes_meubles-1-balcons-1-grande piscine ', 'DLALENDI7',114);
INSERT INTO maisons_vente (id_vente, type_vente, description_vente, adresse_vente, prix_vente,id_client) VALUES('MVAP4','villa','4-chambres 2-douches-1cuisinesmodernes_meubles-1-balcons1-grand couloir1-grand espacejardinage-1-grande cour ', 'DLABONAMOUSSADI',30000000, 115);
INSERT INTO maisons_vente (id_vente, type_vente, description_vente, adresse_vente, prix_vente,id_client) VALUES('MVST11','appartement','4-chambres 2-douches-1cuisinesmodernes_meubles-2-balcons1-grande cour1-grande piscine ', 'DLALOGBESSOU7',10000000,116);
INSERT INTO maisons_vente (id_vente, type_vente, description_vente, adresse_vente, prix_vente,id_client) VALUES('MVCH3','DUPLEX ','3-chambres 2-douches-1cuisinesmodernes_meubles-2-balcons1-grande cour1-grande piscine ', 'YDEBASTOS78',10000000,117);
INSERT INTO maisons_vente (id_vente, type_vente, description_vente, adresse_vente, prix_vente,id_client) VALUES('MVCH4','maison','4-chambres 2-douches-1cuisinesmodernes_meubles-2-balcons1-grande cour ', 'DLA17',1000000000, 118);
INSERT INTO maisons_vente (id_vente, type_vente, description_vente, adresse_vente, prix_vente,id_client) VALUES('MVCH5','immeuble','3-chambres 3-douches-1cuisinesmodernes_meubles-1-balcons ', 'DLAMAKEPE45',250000000, 119);
INSERT INTO maisons_vente (id_vente, type_vente, description_vente, adresse_vente, prix_vente,id_client) VALUES('MVCH6','immeuble','2-chambres 2-douches-1cuisinesmodernes_meubles-1 balcons ', 'DLABONANJO21',2500000000, 120 );
INSERT INTO maisons_vente (id_vente, type_vente, description_vente, adresse_vente, prix_vente,id_client) VALUES('MVCH7','maison','2-chambres 2-douches-1cuisinesmodernes_meubles-1 balcons ', 'YDEBASTOS85',120000000, 121);
INSERT INTO maisons_vente (id_vente, type_vente, description_vente, adresse_vente, prix_vente,id_client) VALUES('MVCH10','DUPLEX ',' 4-chambres2-douches-1cuisinesmodernes_meubles-1-balcons1-grand couloir1-grand espacejardinage-1-grande cour ', 'YDEBASTOS33',250000000, 122);
INSERT INTO maisons_vente (id_vente, type_vente, description_vente, adresse_vente, prix_vente,id_client) VALUES('MVCH11','DUPLEX',' 4-chambres2-douches-1cuisinesmodernes_meubles-1-balcons1-grand couloir1-grand espacejardinage-1-grande cour ', 'YDEDAMAS55' ,250000000,123);



