ALTER TABLE CLIENTS
ADD
CONSTRAINT C_CLIENTS FOREIGN KEY (id_proprietaire) REFERENCES PROPRIETAIRES (id_proprietaire);

ALTER TABLE CLIENTS
ADD
CONSTRAINT C_CLIENTS1 FOREIGN KEY (id_Mlocation) REFERENCES MAISONS_LOCATIONS (id_Mlocation);

