ALTER TABLE HISTORIQUES_VENTE
ADD
CONSTRAINT C_HISTORIQUES_VENTE FOREIGN KEY (id_client) REFERENCES CLIENTS(id_client);

ALTER TABLE HISTORIQUES_VENTE
ADD
CONSTRAINT C_HISTORIQUES_VENTE1 FOREIGN KEY (id_Mvente) REFERENCES MAISONS_VENTE(id_Mvente);