ALTER TABLE HISTORIQUES_LOCATIONS
ADD
CONSTRAINT C_HISTORIQUES_LOCATIONS FOREIGN KEY (id_client) REFERENCES CLIENTS(id_client);

ALTER TABLE HISTORIQUES_LOCATIONS
ADD
CONSTRAINT C_HISTORIQUES_LOCATIONS1 FOREIGN KEY (id_Mlocation) REFERENCES MAISONS_LOCATIONS (id_Mlocation); 